### YamlMime:ModuleUnit
title: Windows developer settings
uid: learn-windows.introduction-w10-dev.4-windows-developer-settings
metadata:
  title: Windows developer settings
  description: TBD
  ms.date: 12/10/2018
  author: JohnKennedy
  ms.author: jken
  ms.topic: interactive-tutorial
  ms.prod: learning-windows
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
    [!include[](includes/4-windows-developer-settings.md)]
